version: '3'
services:
  nakama-hugh:  
    build: .
    image: nakama-hugh 
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >      
        ./nakama --config /nakama-hugh/data/local.yml
    restart: "no"
    volumes:
       - ./data/:/nakama-hugh/data
    expose:
      - "7449"
      - "7450"
      - "7451"
    ports:
      - "7449:7349"
      - "7450:7350"
      - "7451:7351"  
