version: '3' # docker compose 버전 
services:
  mysql:
    container_name: mysql_hugh
    image: mysql       
    command: --lower_case_table_names=2
    ports:
      - 3306:3306 
    environment:      
      MYSQL_ROOT_PASSWORD: jinhyung            
      MYSQL_TCP_PORT: 3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    cap_add: 
      - SYS_NICE
