version: '3'
services:
  nakama-hugh:  
    build: .
    image: nakama-hugh 
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >      
        ./nakama --config /nakama-hugh/data/local.yml
    restart: "no"
    volumes:
       - ./data/:/nakama-hugh/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"  
